name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout frontend
        uses: actions/checkout@v2
        with:
          repository: sine-fdn/pact-catalog-web-app
          token: ${{ secrets.PAT }}
          path: ./frontend
          ref: repo-split
      - name: Restructure frontend files
        run: |
          cd frontend
          echo "Moving files from .pact-catalog-web-app/app to ."
          mv ./pact-catalog-web-app/app/* ./
          echo "Moving .gitignore to ."
          mv ./pact-catalog-web-app/.gitignore ./
          echo "Deleting ./pact-catalog-web-app"
          rm -f -r ./pact-catalog-web-app
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
