name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout frontend
        run: cd frontend
        run: git clone --branch repo-split git@github.com:sine-fdn/pact-catalog-web-app.git
        run: echo "Moving files from .pact-catalog-web-app/app to ."
        run: mv ./pact-catalog-web-app/app/* ./
        run: echo "Moving .gitignore to ."
        run: mv ./pact-catalog-web-app/.gitignore ./
        run: echo "Deleting ./pact-catalog-web-app"
        run: rm -f -r ./pact-catalog-web-app
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
